// Code generated by BobGen psql v0.15.6. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"

	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker"
	models "github.com/nicjohnson145/mixer/mixerserver/internal/storage/models"
	"github.com/stephenafamo/bob"
)

type MixerMigrationMod interface {
	Apply(*MixerMigrationTemplate)
}

type MixerMigrationModFunc func(*MixerMigrationTemplate)

func (f MixerMigrationModFunc) Apply(n *MixerMigrationTemplate) {
	f(n)
}

type MixerMigrationModSlice []MixerMigrationMod

func (mods MixerMigrationModSlice) Apply(n *MixerMigrationTemplate) {
	for _, f := range mods {
		f.Apply(n)
	}
}

// MixerMigrationTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type MixerMigrationTemplate struct {
	Version func() int64
	Dirty   func() bool

	f *factory
}

// Apply mods to the MixerMigrationTemplate
func (o *MixerMigrationTemplate) Apply(mods ...MixerMigrationMod) {
	for _, mod := range mods {
		mod.Apply(o)
	}
}

// toModel returns an *models.MixerMigration
// this does nothing with the relationship templates
func (o MixerMigrationTemplate) toModel() *models.MixerMigration {
	m := &models.MixerMigration{}

	if o.Version != nil {
		m.Version = o.Version()
	}
	if o.Dirty != nil {
		m.Dirty = o.Dirty()
	}

	return m
}

// toModels returns an models.MixerMigrationSlice
// this does nothing with the relationship templates
func (o MixerMigrationTemplate) toModels(number int) models.MixerMigrationSlice {
	m := make(models.MixerMigrationSlice, number)

	for i := range m {
		m[i] = o.toModel()
	}

	return m
}

// setModelRels creates and sets the relationships on *models.MixerMigration
// according to the relationships in the template. Nothing is inserted into the db
func (t MixerMigrationTemplate) setModelRels(o *models.MixerMigration) {}

// BuildSetter returns an *models.MixerMigrationSetter
// this does nothing with the relationship templates
func (o MixerMigrationTemplate) BuildSetter() *models.MixerMigrationSetter {
	m := &models.MixerMigrationSetter{}

	if o.Version != nil {
		m.Version = omit.From(o.Version())
	}
	if o.Dirty != nil {
		m.Dirty = omit.From(o.Dirty())
	}

	return m
}

// BuildManySetter returns an []*models.MixerMigrationSetter
// this does nothing with the relationship templates
func (o MixerMigrationTemplate) BuildManySetter(number int) []*models.MixerMigrationSetter {
	m := make([]*models.MixerMigrationSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.MixerMigration
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MixerMigrationTemplate.Create
func (o MixerMigrationTemplate) Build() *models.MixerMigration {
	m := o.toModel()
	o.setModelRels(m)

	return m
}

// BuildMany returns an models.MixerMigrationSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use MixerMigrationTemplate.CreateMany
func (o MixerMigrationTemplate) BuildMany(number int) models.MixerMigrationSlice {
	m := make(models.MixerMigrationSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableMixerMigration(m *models.MixerMigrationSetter) {
	if m.Version.IsUnset() {
		m.Version = omit.From(random[int64](nil))
	}
	if m.Dirty.IsUnset() {
		m.Dirty = omit.From(random[bool](nil))
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.MixerMigration
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *MixerMigrationTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.MixerMigration) (context.Context, error) {
	var err error

	return ctx, err
}

// Create builds a mixerMigration and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *MixerMigrationTemplate) Create(ctx context.Context, exec bob.Executor) (*models.MixerMigration, error) {
	_, m, err := o.create(ctx, exec)
	return m, err
}

// create builds a mixerMigration and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted model
func (o *MixerMigrationTemplate) create(ctx context.Context, exec bob.Executor) (context.Context, *models.MixerMigration, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableMixerMigration(opt)

	m, err := models.MixerMigrationsTable.Insert(ctx, exec, opt)
	if err != nil {
		return ctx, nil, err
	}
	ctx = mixerMigrationCtx.WithValue(ctx, m)

	ctx, err = o.insertOptRels(ctx, exec, m)
	return ctx, m, err
}

// CreateMany builds multiple mixerMigrations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o MixerMigrationTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.MixerMigrationSlice, error) {
	_, m, err := o.createMany(ctx, exec, number)
	return m, err
}

// createMany builds multiple mixerMigrations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// this returns a context that includes the newly inserted models
func (o MixerMigrationTemplate) createMany(ctx context.Context, exec bob.Executor, number int) (context.Context, models.MixerMigrationSlice, error) {
	var err error
	m := make(models.MixerMigrationSlice, number)

	for i := range m {
		ctx, m[i], err = o.create(ctx, exec)
		if err != nil {
			return ctx, nil, err
		}
	}

	return ctx, m, nil
}

// MixerMigration has methods that act as mods for the MixerMigrationTemplate
var MixerMigrationMods mixerMigrationMods

type mixerMigrationMods struct{}

func (m mixerMigrationMods) RandomizeAllColumns(f *faker.Faker) MixerMigrationMod {
	return MixerMigrationModSlice{
		MixerMigrationMods.RandomVersion(f),
		MixerMigrationMods.RandomDirty(f),
	}
}

// Set the model columns to this value
func (m mixerMigrationMods) Version(val int64) MixerMigrationMod {
	return MixerMigrationModFunc(func(o *MixerMigrationTemplate) {
		o.Version = func() int64 { return val }
	})
}

// Set the Column from the function
func (m mixerMigrationMods) VersionFunc(f func() int64) MixerMigrationMod {
	return MixerMigrationModFunc(func(o *MixerMigrationTemplate) {
		o.Version = f
	})
}

// Clear any values for the column
func (m mixerMigrationMods) UnsetVersion() MixerMigrationMod {
	return MixerMigrationModFunc(func(o *MixerMigrationTemplate) {
		o.Version = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mixerMigrationMods) RandomVersion(f *faker.Faker) MixerMigrationMod {
	return MixerMigrationModFunc(func(o *MixerMigrationTemplate) {
		o.Version = func() int64 {
			return random[int64](f)
		}
	})
}

func (m mixerMigrationMods) ensureVersion(f *faker.Faker) MixerMigrationMod {
	return MixerMigrationModFunc(func(o *MixerMigrationTemplate) {
		if o.Version != nil {
			return
		}

		o.Version = func() int64 {
			return random[int64](f)
		}
	})
}

// Set the model columns to this value
func (m mixerMigrationMods) Dirty(val bool) MixerMigrationMod {
	return MixerMigrationModFunc(func(o *MixerMigrationTemplate) {
		o.Dirty = func() bool { return val }
	})
}

// Set the Column from the function
func (m mixerMigrationMods) DirtyFunc(f func() bool) MixerMigrationMod {
	return MixerMigrationModFunc(func(o *MixerMigrationTemplate) {
		o.Dirty = f
	})
}

// Clear any values for the column
func (m mixerMigrationMods) UnsetDirty() MixerMigrationMod {
	return MixerMigrationModFunc(func(o *MixerMigrationTemplate) {
		o.Dirty = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m mixerMigrationMods) RandomDirty(f *faker.Faker) MixerMigrationMod {
	return MixerMigrationModFunc(func(o *MixerMigrationTemplate) {
		o.Dirty = func() bool {
			return random[bool](f)
		}
	})
}

func (m mixerMigrationMods) ensureDirty(f *faker.Faker) MixerMigrationMod {
	return MixerMigrationModFunc(func(o *MixerMigrationTemplate) {
		if o.Dirty != nil {
			return
		}

		o.Dirty = func() bool {
			return random[bool](f)
		}
	})
}
