services:
  postgres:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_DB=mixer
      - POSTGRES_PASSWORD=mixer_pass
      - POSTGRES_USER=mixer_usr
    ports:
    - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 1s
      retries: 30
    volumes:
    - pg_data:/var/lib/postgresql/data
  mixer:
    build:
      context: .
    image: nicjohnson145/mixerserver:${CI_COMMIT_REF_NAME:-develop}
    environment:
      DATABASE_HOST: postgres
    depends_on:
    - postgres
volumes:
  pg_data: {}
