services:
  postgres:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_DB=mixer
      - POSTGRES_PASSWORD=mixer_pass
      - POSTGRES_USER=mixer_usr
    ports:
    - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 1s
      retries: 30
    volumes:
    - pg_data:/var/lib/postgresql/data
  mixer:
    build:
      context: .
    image: nicjohnson145/mixerserver:${CI_COMMIT_REF_NAME:-latest}
    environment:
      DATABASE_HOST: postgres
      PROTECT_REGISTER: "false"
    ports:
    - 50051:50051
    depends_on:
    - postgres
  gateway:
    build:
      context: .
    image: nicjohnson145/mixerserver:${CI_COMMIT_REF_NAME:-latest}
    command:
    - gateway
    environment:
      GATEWAY_GRPC_HOST: "mixer"
    ports:
    - 8080:8080
    depends_on:
    - mixer
volumes:
  pg_data: {}
