// Code generated by BobGen psql v0.15.6. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
)

var TableNames = struct {
	Drinks          string
	MixerMigrations string
	Usrs            string
	UsrSettings     string
}{
	Drinks:          "drink",
	MixerMigrations: "mixer_migrations",
	Usrs:            "usr",
	UsrSettings:     "usr_setting",
}

var ColumnNames = struct {
	Drinks          drinkColumnNames
	MixerMigrations mixerMigrationColumnNames
	Usrs            usrColumnNames
	UsrSettings     usrSettingColumnNames
}{
	Drinks: drinkColumnNames{
		ID:               "id",
		Name:             "name",
		Username:         "username",
		PrimaryAlcohol:   "primary_alcohol",
		PreferredGlass:   "preferred_glass",
		Ingredients:      "ingredients",
		Instructions:     "instructions",
		Notes:            "notes",
		Publicity:        "publicity",
		UnderDevelopment: "under_development",
		Tags:             "tags",
		Favorite:         "favorite",
	},
	MixerMigrations: mixerMigrationColumnNames{
		Version: "version",
		Dirty:   "dirty",
	},
	Usrs: usrColumnNames{
		Username: "username",
		Password: "password",
	},
	UsrSettings: usrSettingColumnNames{
		Username: "username",
		Key:      "key",
		Value:    "value",
	},
}

var (
	SelectWhere = Where[*dialect.SelectQuery]()
	InsertWhere = Where[*dialect.InsertQuery]()
	UpdateWhere = Where[*dialect.UpdateQuery]()
	DeleteWhere = Where[*dialect.DeleteQuery]()
)

func Where[Q psql.Filterable]() struct {
	Drinks          drinkWhere[Q]
	MixerMigrations mixerMigrationWhere[Q]
	Usrs            usrWhere[Q]
	UsrSettings     usrSettingWhere[Q]
} {
	return struct {
		Drinks          drinkWhere[Q]
		MixerMigrations mixerMigrationWhere[Q]
		Usrs            usrWhere[Q]
		UsrSettings     usrSettingWhere[Q]
	}{
		Drinks:          DrinkWhere[Q](),
		MixerMigrations: MixerMigrationWhere[Q](),
		Usrs:            UsrWhere[Q](),
		UsrSettings:     UsrSettingWhere[Q](),
	}
}
